name       : sudo
version    : 1.8.22
release    : 16
source     :
    - https://www.sudo.ws/dist/sudo-1.8.22.tar.gz : 7256cb27c20883b14360eddbd17f98922073d104b214cf65aeacf1d9c9b9fd02
homepage   : http://www.sudo.ws/
license    : ISC
summary    : Run commands as a privileged user
component  : system.base
description: |
    The Sudo package allows a system administrator to give certain users (or groups of users) the ability to run some (or all) commands as root or another user while logging the commands and arguments.
setup      : |
    %patch -p1 < $pkgfiles/do-not-install-sample-sudoers-etc-sudoers.dist.patch
    %configure --with-all-insults \
               --with-env-editor \
               --with-tty-tickets
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/var
    # sysusers group it
    install -D -m 00644 $pkgfiles/sudo.sysusers $installdir/%libdir%/sysusers.d/sudo.conf
    # sudoers file
    install -D -m 00400 $pkgfiles/sudoers $installdir/etc/sudoers
    # sudo pam
    install -D -m 00644 $pkgfiles/pam.d/sudo $installdir/etc/pam.d/sudo
